mjansson/rpmalloc

- README.md
- build/ninja/gcc.py
- rpmalloc/rpmalloc.c
Define four different cache control presets, from unlimited to no cache, to enable easy configuration depending on performance or size prioritization.
> Cache presets

- rpmalloc/rpmalloc.c
Reduce span classes by 2 and fix size class merging
> Reduce span classes

- README.md
- rpmalloc/rpmalloc.c
- rpmalloc/rpmalloc.h
> Enable 64KiB page size and improve cache/unmap control

- build/ninja/clang.py
- build/ninja/gcc.py
- rpmalloc/malloc.c
- rpmalloc/rpmalloc.c
- linkage fix
- huge page support.
> Improve FreeBSD support

- build/ninja/clang.py
- build/ninja/gcc.py
- rpmalloc/malloc.c
- rpmalloc/rpmalloc.c
backtrace is not part of the base system.
fixing little FreeBSD while at it.
> Little update for OpenBSD support.

- test/thread.c
> Releaxing memory barriers on x86 arch.

- CHANGELOG
- build/ninja/msvc.py
- rpmalloc/malloc.c
- rpmalloc/new.cc
- rpmalloc/rpmalloc.c
- rpmalloc/rpmalloc.h
- test/main.c
- Improved cross thread deallocations by using per-span deferred free list (Issue #63)
- Streamline fast paths in both alloc and dealloc by refactoring to get rid of conditionals
> Improved cross thread frees and optimize allocation fast paths

- rpmalloc/rpmalloc.c
Fixes crashes in OOM situations.
> Add missing NULL checks to the allocation path.

- README.md
Thank you for the library, I found it very useful and the [performance](https://github.com/nxrighthere/Rpmalloc-CSharp#performance) is great.
> Mention a C# wrapper

- rpmalloc/rpmalloc.c
- rpmalloc/rpmalloc.h
- test/main.c
- test/thread.c
- test/thread.h
> Update atomics to avoid explicit barriers

- rpmalloc/malloc.c
malloc_usable_size different signature.
> Android build fix proposal.

- build/ninja/clang.py
- build/ninja/gcc.py
- build/ninja/platform.py
- build/ninja/toolchain.py
- rpmalloc/rpmalloc.c
> Sun OS platforms (legacy solaris but illumos based ones too).

- CHANGELOG
- rpmalloc/malloc.c
- rpmalloc/rpmalloc.c
- test/main-override.cc
> fix pvalloc and rearrange heap release code

- rpmalloc/rpmalloc.c
Possibility to align the page for huge page setting.
> MAP_ALIGNED flag support (NetBSD).

- build/ninja/clang.py
- build/ninja/generator.py
- build/ninja/toolchain.py
clang with MUSL does not support it, some platform this support
might be broken (e.g. Android).
> clang toolchain making LTO support optional.

- rpmalloc/rpmalloc.c
> Fix includes on MinGW-w64

- build/ninja/clang.py
- build/ninja/gcc.py
- build/ninja/platform.py
- build/ninja/toolchain.py
- rpmalloc/rpmalloc.c
Avoiding atomic_add* conflicts, TLS model unsupported on this platform.
> Haiku build fix.

- build/ninja/clang.py
- build/ninja/gcc.py
- rpmalloc/rpmalloc.c
madvise requiring a so specific preprocessor set in this case
it is lot easier to present the symbol.
ar in this platform does not support the deterministic flag.
> Illumos/Solaris build fix.

- rpmalloc/rpmalloc.c
mainly for cpu power saving/being more available for background tasks.
Noticed a little but consistent performance increase on ARM.
> cpu yield on global contention

- rpmalloc/rpmalloc.c
rolls out page freeing until we are sur it's complete.
> Mac OS page clearing implementation update.

- rpmalloc/rpmalloc.c
- rpmalloc/rpmalloc.h
- test/main.c
when looking up to /proc/<pid>/maps, the anonymous page address range
stands out with an ID as `[anon:<ID>]`.
> named page new option for Linux 5.17/android.

- rpmalloc/rpmalloc.c
Unlike their non inline counterparts, no extra calls are generated
at LLVM IR time but work only on compile time sizes so we sort
of replicate this constraint for other compilers.
> Clang's __builtin_memset_inline/__builtin_memcpy_inline introduction.

- rpmalloc/rpmalloc.c
Count spans in overflow list of global cache when unlimited cache is enabled.
> feat(stats): count overflow list when unlimited cache is enabled
