rpmalloc/rpmalloc.c
I had problems building rpmalloc using GCC 7.2.0 on Slackware ARM, and got many of these errors:
Error: selected processor does not support `dmb sy' in ARM mode
Error: selected processor does not support `dmb st' in ARM mode
Looking at https://gcc.gnu.org/ml/gcc-patches/2014-11/msg01272.html, it seems that it is safe to replace `dmb sy` (and I assume) `dmb st` with `dmb ish`. I could then compile rpmalloc and everything seems to work fine (I could use programs that depend on rpmalloc fine).
Note that I haven't run any sort of extensive tests, and I'm not entirely sure if `dmb ish` is the correct replacement for `dmb st`, but this should work.
=> Use dmb ish instead of dmb st and dmb sy

rpmalloc/rpmalloc.c
If assert.h has been included via a prefix header then redefining it will cause a macro redefinition warning.
This could be handled by setting ENABLE_ASSERTS based on the existing value of NDEBUG, but this patch assumes that ENABLE_ASSERTS should win out and so any existing assert() is removed before the no-op version is defined.
=> Avoid redefining assert macro.

CHANGELOG, README.md, rpmalloc/rpmalloc.c, rpmalloc/rpmalloc.h
Allow super spans to be pre-reserved and broken up on free to reduce number of system calls and allow freed spans from large allocations to be used as cache spans for small/medium allocations
=> Super spans

rpmalloc/rpmalloc.c
If mmap returns NULL, it probably means we are out of memory (or address space.) Just return NULL instead of crashing in this case.
=> Handle OOM gracefully.

build/ninja/generator.py
This breaks build on Travis but not on my own system (which weirdly should be running the exact same versions of both the OS and python). Appears to be typo?
=> Configuration script error?

rpmalloc/rpmalloc.c
* Saw this attempting to build rpmalloc for riscv64 under Haiku.
* __LP64__ defined on gcc + clang
* __LLP64__ defined on windows
=> rpmalloc: Improve 64-bit check to be more generic

rpmalloc/rpmalloc.c
Minor optimization, keep the current active span for the size class on owner heap even when fully freed to avoid ping-pong of span between cache list and active span
=> Keep active span when fully freed

build/ninja/clang.py, build/ninja/gcc.py
Like described here https://github.com/mjansson/rpmalloc/issues/124,
the porpused solution in the branch mjansson/cross-compile does break honoring **CFLAGS** because the var in build.ninja cmoreflags is used for other purposes and therfore can not be used for adding flags from the environment.
So simply do not change usage from vars and add XXXflagsenv for appending custom flags to the build commands.
Signed-off-by: Johann Neuhauser <johann@it-neuhauser.de>
=> Add cross compile setup from environment

rpmalloc/malloc.c
`aligned_alloc` only exists in MacOS 10.15+
=> fix compilation when targeting OSX < 10.15

rpmalloc/rpmalloc.c
* set define to allow "zu" format specifier
* determine size of void* at compile-time with UINTPTR_MAX,
prevents warning about overflow
build system still fails to create a DLL due to assuming microsoft tools, but the object file gets created
=> Fix compilation with mingw

rpmalloc/rpmalloc.c
asm token not recognised by none of the compilers (raspberry).
=> Build on ARM for the process id register assembly.

README.md, rpmalloc/rpmalloc.c, test/main.c
- Rename internal methods to have rpmalloc prefix to make callstacks easier to read
- Improve grouping of functions based on context
=> Refactor for readability

build/ninja/android.py, build/ninja/clang.py, build/ninja/toolchain.py, build/ninja/xcode.py
This was causing errors on macOS with python3 since it returned
a byte object instead of a string there.
I have tested these changes with both Python 2 and 3 on macOS.
=> Decode return values from subprocess.check_output

test/main-override.cc, test/main.c, test/thread.c
mingw-w64 is case sensitive for include files when cross compiling on Linux, this fixes the compile error:
```
rpmalloc/rpmalloc.c:123:12: fatal error: Windows.h: No such file or directory
123 | #  include <Windows.h>
```
=> Fix windows include on mingw-w64

test/thread.c
If nanosleep is interrupted, retry with the "remaining" time for sleeping the requested time.
Signed-off-by: Ponnuvel Palaniyappan <pponnuvel@gmail.com>
=> Retry nanosleep on EINTR

test/thread.c
I just realized that there's a bug in my previous PR (#190).
If nanosleep fails for something other than EINTR, it could potentially enter an infinite loop.
Signed-off-by: Ponnuvel Palaniyappan <pponnuvel@gmail.com>
=> Fix a bug retry on sleep logic

rpmalloc/rpmalloc.c
`_memory_global_reserve` is marked as subspan only in `_rpmalloc_global_get_reserved_spans()`. So we should mark it explicitly before we call `_rpmalloc_span_unmap()` to unmap it directly.
=> Mark subspan for global reserved span before unmap it

rpmalloc/rpmalloc.c
In `rpmalloc_heap_alloc()` and `rpmalloc_heap_aligned_alloc()`, `ptr` is not defined.
=> Fix a bug which references undefined variable `ptr`

rpmalloc/rpmalloc.h
The allocate size of `rpmalloc_heap_aligned_realloc()` is specified by `size` whose number is 4.
=> Fix wrong alloc_size for rpmalloc_heap_aligned_realloc

rpmalloc/rpmalloc.c
Use `memset()` to initialize all fields in `heap_t`.
Fix #192
=> Initialize heap_t struct after allocate it

rpmalloc/rpmalloc.h
There is a small typo in rpmalloc/rpmalloc.h.
Should read `implemented` rather than `imlemented`.
=> docs: fix simple typo, imlemented -> implemented

rpmalloc/rpmalloc.c
Fix a minor conversion error that prevents the library from being
compiled with very recent versions of Clang, which provide -Wconversion,
enabled as part of -Weverything (as set by the rpmalloc build).
The issue was that heap->id is an int32_t value, so the compiler was
complaining that the code was trying to implicitly convert a signed
32-bit integer into an unsigned 64-bit one.
=> Fix minor implicit conversion errors.

rpmalloc/rpmalloc.c
=> Soften the error handling when out of memory, aborting still

build/ninja/platform.py, rpmalloc/malloc.c
the system does not contain BSD keyword but is truly one.
asking proper pthread symbol too.
=> DragonFlyBSD support.

build/ninja/clang.py
gcc does not have this issue, the "problematic" macro
was #define stderr (stderr)
=> Fix macro expansion for clang due to musl based distros.

rpmalloc/rpmalloc.c
those pages can be reused at will by other needs.
Thus, the memory usage reported by the OS decreases to the expected amount.
Before change, rpmalloc-test the sample utility reported about 692 MB,
after this chang it is about 305 MB.
=> On Darwin using MADV_FREE_REUSABLE to notify the system

rpmalloc/rpmalloc.c
Normally tailored for each model but here the least common
denominator as reading the Conditions Code Register couple of time.
=> CPU spin equivalent for sparc.

rpmalloc/rpmalloc.c
The iOS simulator runs binaries under the Mach kernel, which maps thread specific memory using the GS register.
The old code used FS instead which caused a null pointer dereference when debugging in the simulator. I think this bug was introduced in #172 to fix a compile error when targeting ARM.
=> Fixed get_thread_id for iOS simulator

rpmalloc/rpmalloc.c
In the current version, rpmalloc will adopt deferred span cache list if
and only if the span_count == 1. This may cause memory leak in some
situations where the allocator thread allocate large blocks only and the
block is freed in another thread. So we try to adopt the deferred list
even when span_count != 1.
Besides, we also adopt deferred list when allocating huge blocks for the
same reason.
=> fix(deferred): adopt the deferred span cache list when span_count != 1

rpmalloc/rpmalloc.c
As defined by ARM toolchains, see https://godbolt.org/z/536hzj
I believe `__ARM_ARCH__` with trailing underscores is only defined in some platform-specific header files, derived from `__ARM_ARCH_xy__` macros for the specific architecture, but I'm not 100% sure. Yet I've seen the `__ARM_ARCH` variety pre-defined by all ARMv7 toolchains I tested, without the need for any system includes.
=> Use __ARM_ARCH macro without trailing underscores

rpmalloc/rpmalloc.c
GCC defines \_\_GNUC__ instead of \_\_GCC__
=> Fix GCC detection

rpmalloc/rpmalloc.c
Adopt deferred cache list when allocating huge block to avoid worst condition where the allocator thread allocates huge block only, and those huge blocks will never be dellocated if they are freed in another thread.
=> feat(adopt-deferred): adopt deferred list when allocating huge block

CHANGELOG, rpmalloc/rpmalloc.c
- Avoids excessive memory use by constantly splitting multi-spans into single spans through the reserve field in some allocation patterns
- Use MADV_DONTNEED over MADV_FREE to release physical pages
- Add some extra global cache statistics
=> tweak cache and prefer cache over re-reserving spans in thread heap

rpmalloc/rpmalloc.c
This fix issue #256
With this patch I can use rpmalloc on MSYS.
=> Fix crash on MSYS2

rpmalloc/rpmalloc.c
Increase mapped_pages counter only after memory_map operation succeeds
(by checking the address against NULL). This can address a false positive
case of memory leak test when mmap() returns NULL.
=> fix(stats): increase mapped_pages only after memory_map succeeds

rpmalloc/rpmalloc.c
Fix the race condition on `list_size` between `_rpmalloc_deallocate_direct_small_or_medium` and `_rpmalloc_deallocate_defer_small_or_medium` reported in #280 and #281, by synchronizing on the `free_list_deferred` pointer with acquire/release semantics.
=> synchronize deferred list size before free span

build/ninja/clang.py
Unfortunately AVX* instructions are unsupported.
=> Fixes SIGILL on macOs rosetta mode (x86_64)

rpmalloc/rpmalloc.c
clang-cl doesn't define GNUC but it does define __clang__. So
check for both when deciding if we should use the builtin inline memcpy
=> clang-cl: Use builtin intrinsics for clang-cl as well

build/ninja/clang.py
In Clang 15 `-funit-at-a-time` gives the following error:
```
clang-15: error: optimization flag '-funit-at-a-time' is not supported [-Werror,-Wignored-optimization-argument]
```
This flag doesn't do anything in clang even before, so we can drop it without any problems.
=> Fix compatibility with Clang 15

rpmalloc/rpmalloc.c
This seems to assume that `heap` is not null, despite `_rpmalloc_heap_allocate_new()` being capable of returning null.
Not sure whether this check should be here or in `_rpmalloc_heap_cache_adopt_deferred`.
=> heap_allocate: check for null before adopting deferred

rpmalloc/rpmalloc.c
Use assign operator will only record the size in the last size class.
=> fix: accumulate sizecache & spancache in heap stats

rpmalloc/malloc.c
This PR copies the attributes used in rpmalloc.h to the alias definitions in malloc.c to fix the -Wmissing-attributes.
Closes #296
=> Fix GCC -Wmissing-attributes warnings for -DENABLE_OVERRIDE=1

rpmalloc/rpmalloc.c, rpmalloc/rpmalloc.h
Adding a new API call which allows for querying which first-class heap a given address was allocated on. This is useful when doing reallocs or frees in an environment that uses a mixture of thread-local and manually-managed first-class heaps, by being able to find what the source heap for an allocation was, and deciding what behaviour should be performed in light of that.
=> Add "rpmalloc_get_heap_for_ptr"

rpmalloc/rpmalloc.c
The allocator should check the global cache for an available span before extracting a span of memory from the reserved memory to avoid cache bloating. Besides, extracting from reserved memory eagerly may also increase the degree of memory fragmentation.
=> perf: check global cache before extracting from reserved memory

rpmalloc/rpmalloc.c
PR #347 fixed/removed using the `"initial-exec"` TLS model for Android which is no longer compatible since LLVM 17 where ELF TLS is enabled by default for API level 29.
It opted to instead enable `"local-dynamic"`, but only if the minimum API level is 29 _and_ the NDK is version 26 or higher, and otherwise doesn't define a TLS model at all.  However, this did not consider simple build cases where e.g. `clang --target aarch64-linux-android29` may be invoked without ever including an NDK header that sets `__NDK_MAJOR__ 26` or higher (noting that LLVM 17 is used since r26): https://togithub.com/mjansson/rpmalloc/pull/347#discussion_r1912096361
Instead, check if the `__clang_major__` define is `17` or higher, but also keep the original comparison in place just in case even if it's …
=> android: Enable `tls_model("local_dynamic")` for NDK-less builds on LLVM >= 17

rpmalloc/rpmalloc.c
Only certain flavors of Windows support GetLargePageMinimum (specifically WINAPI_PARTITION_APP and WINAPI_PARTITION_SYSTEM a.k.a Application or OneCore family
For the others we can default to 2MB, as that is the typical minimum size according to the docs
=> Avoid compiling call to GetLargePageMinimum when it's not available
